import { PlaceRepository } from '../repositories/PlaceRepository';
import { TourRepository } from '../repositories/TourRepository';
import { HotelRepository } from '../repositories/HotelRepository';
import { TipRepository } from '../repositories/TipRepository';
import { ItineraryRepository } from '../repositories/ItineraryRepository';
import { Place, PlaceCategory, Tour, Hotel, PracticalTip, TipCategory, Itinerary, ItineraryType, ItineraryTheme, TransportMode, Difficulty } from '../../types';

const samplePlaces: Omit<Place, 'createdAt' | 'updatedAt'>[] = [
  {
    id: '1',
    name: 'Prague Castle',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0910966,
    longitude: 14.4016165,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '2',
    name: 'St. Vitus Cathedral',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0908918,
    longitude: 14.4005114,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '3',
    name: 'Golden Lane',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0918218,
    longitude: 14.4038298,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '4',
    name: 'Petřín Tower',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.083527,
    longitude: 14.3950837,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '5',
    name: 'St. Nicholas Church',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0880269,
    longitude: 14.4034704,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '6',
    name: 'Lennon Wall',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0862506,
    longitude: 14.4067918,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '7',
    name: 'Charles Bridge',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0864771,
    longitude: 14.4114366,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '8',
    name: 'Old Town Square',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0875692,
    longitude: 14.4211874,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '9',
    name: 'Klementinum Library',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.086598,
    longitude: 14.416019,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '10',
    name: 'Astronomical Clock',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0870215,
    longitude: 14.4207065,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '11',
    name: 'Prague Jewish Quarter',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0907869,
    longitude: 14.4192286,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '12',
    name: 'Powder Tower',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.087273,
    longitude: 14.4277887,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '13',
    name: 'Municipal House',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0877208,
    longitude: 14.4277908,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '14',
    name: 'Golden Lane',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.091822,
    longitude: 14.40383,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '15',
    name: 'Wenceslas Square',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0810226,
    longitude: 14.4279917,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '16',
    name: 'Dancing House',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0754031,
    longitude: 14.4141786,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '17',
    name: 'National Museum Building',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.SIGHTSEEING,
    latitude: 50.0792502,
    longitude: 14.4304989,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '18',
    name: 'Trója Chateau',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.116456,
    longitude: 14.412874,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '19',
    name: 'Fanta\'s Building of Prague Main Station',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.0832251,
    longitude: 14.4352955,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '20',
    name: 'Vítkov Hill',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.0883976,
    longitude: 14.4491654,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '21',
    name: 'Nový Svět',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.090924,
    longitude: 14.391383,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '22',
    name: 'Žižkov Television Tower',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.081047,
    longitude: 14.4511421,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '23',
    name: 'Old Jewish Cemetery',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.0894826,
    longitude: 14.4174435,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '24',
    name: 'Prague Náplavka Waterfront',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.071384,
    longitude: 14.413909,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '25',
    name: 'Church of the Most Sacred Heart of Our Lord',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.0779995,
    longitude: 14.4502908,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '26',
    name: 'Museum of Alchemists and Magicians of Old Prague',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.08806,
    longitude: 14.39867,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '27',
    name: 'Prague Meridian',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.087468,
    longitude: 14.421342,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '28',
    name: 'Church of Our Lady of the Snows',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.082995,
    longitude: 14.423577,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '29',
    name: 'Břevnov Monastery',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.084683,
    longitude: 14.356886,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '30',
    name: 'Hunger Wall',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.080734,
    longitude: 14.402107,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '31',
    name: 'Church of St. Martin in the Wall',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.08313,
    longitude: 14.419846,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '32',
    name: 'St. Cyril and Methodius Church',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.091142,
    longitude: 14.448161,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '33',
    name: 'Vyšehrad',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.062934,
    longitude: 14.417195,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '34',
    name: 'Thunovská street',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.089108,
    longitude: 14.402472,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '35',
    name: 'Náměstí Míru',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.HIDDEN_GEMS,
    latitude: 50.075423,
    longitude: 14.436801,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '36',
    name: 'The smallest house in Prague',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.BIZARRE,
    latitude: 50.0917364,
    longitude: 14.424262,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '37',
    name: 'Prague\'s narrowest alley',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.BIZARRE,
    latitude: 50.0879538,
    longitude: 14.4095422,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '38',
    name: 'Upside-Down Horse Sculpture',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.BIZARRE,
    latitude: 50.081305,
    longitude: 14.425293,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '39',
    name: 'Franz Kafka - Rotating Head',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.BIZARRE,
    latitude: 50.0816514,
    longitude: 14.420821,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '40',
    name: 'Kampa Park - Faceless Babies',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.BIZARRE,
    latitude: 50.08414,
    longitude: 14.408347,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '41',
    name: 'Paternoster Nová radnice (New City Hall)',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.BIZARRE,
    latitude: 50.087041,
    longitude: 14.418,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '42',
    name: 'Cubist Lamp Post',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.BIZARRE,
    latitude: 50.083326,
    longitude: 14.423685,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '43',
    name: 'The Park of Brutalist Miniatures',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.BIZARRE,
    latitude: 50.0920419,
    longitude: 14.408995,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '44',
    name: 'Peeing Sculptures',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.BIZARRE,
    latitude: 50.088087,
    longitude: 14.4102414,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '45',
    name: 'Páternoster - Prague City Hall',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.BIZARRE,
    latitude: 50.0871338,
    longitude: 14.4179017,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '46',
    name: 'Brown Nosers',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.BIZARRE,
    latitude: 50.073796,
    longitude: 14.394319,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '47',
    name: 'Old Town Hall Tower',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.08709,
    longitude: 14.420664,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '48',
    name: 'Old Town Bridge Tower',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.086231,
    longitude: 14.413614,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '49',
    name: 'Bedřich Smetana Statue',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.085335,
    longitude: 14.412924,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '50',
    name: 'Petřín Observation Tower',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.083527,
    longitude: 14.395084,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '51',
    name: 'Letná Viewpoint - Hanavský Pavilion',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.093677,
    longitude: 14.412615,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '52',
    name: 'Letná Viewpoint II - Metronome',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.094744,
    longitude: 14.415941,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '53',
    name: 'Letná Viewpoint III - Letná Beer Garden',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.096146,
    longitude: 14.425743,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '54',
    name: 'St. Vitus Cathedral Tower',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.090656,
    longitude: 14.400436,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '55',
    name: 'View from Zámecké schody',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.089243,
    longitude: 14.398494,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '56',
    name: 'St. Nicholas Bell Tower',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.087952,
    longitude: 14.403646,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '57',
    name: 'Vyšehrad Fortress',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.063682,
    longitude: 14.41645,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '58',
    name: 'The Dancing House Rooftop',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.075403,
    longitude: 14.414179,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '59',
    name: 'Lesser Town Bridge Tower',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.087323,
    longitude: 14.40686,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '60',
    name: 'The Orchard in Strahov Garden',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.087027,
    longitude: 14.390334,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '61',
    name: 'Vrtba Garden',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.086644,
    longitude: 14.402878,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '62',
    name: 'The Powder Tower',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.087273,
    longitude: 14.427789,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '63',
    name: 'Klementinum Astronomical Tower',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.086158,
    longitude: 14.41659,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '64',
    name: 'Terasa U Prince',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.086444,
    longitude: 14.42011,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '65',
    name: 'Riegrovy Sady Park',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.079695,
    longitude: 14.44023,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '66',
    name: 'Vítkov Hill (National Memorial)',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.08823,
    longitude: 14.44809,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '67',
    name: 'Žižkov Television Tower',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.VIEWPOINTS,
    latitude: 50.081333,
    longitude: 14.451064,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '68',
    name: 'Wallenstein Garden',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.PARKS,
    latitude: 50.090403,
    longitude: 14.4078806,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '69',
    name: 'Botanická zahrada Přírodovědecké fakulty UK',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.PARKS,
    latitude: 50.071384,
    longitude: 14.421489,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '70',
    name: 'Kinsky Garden',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.PARKS,
    latitude: 50.079558,
    longitude: 14.39872,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '71',
    name: 'Franciscan Gardens',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.PARKS,
    latitude: 50.082083,
    longitude: 14.423969,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '72',
    name: 'Divoká Šárka',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.PARKS,
    latitude: 50.093302,
    longitude: 14.325004,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '73',
    name: 'Grébovka (Havlíčkovy sady)',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.PARKS,
    latitude: 50.06947,
    longitude: 14.444992,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '74',
    name: 'Stromovka Park',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.PARKS,
    latitude: 50.1063295,
    longitude: 14.4191289,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '75',
    name: 'Vojanovy Sady',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.PARKS,
    latitude: 50.0888756,
    longitude: 14.4090669,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '76',
    name: 'Riegrovy sady',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.PARKS,
    latitude: 50.0802844,
    longitude: 14.4415606,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '77',
    name: 'National Theatre',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0804438,
    longitude: 14.4138224,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '78',
    name: 'Museum of Communism',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0879687,
    longitude: 14.4299824,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '79',
    name: 'Illusion Art Museum Prague',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0851495,
    longitude: 14.4217451,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '80',
    name: 'Prague Glass Experience',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.086659,
    longitude: 14.4197177,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '81',
    name: 'The World of Banksy',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0862514,
    longitude: 14.4202595,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '82',
    name: 'Black Light Theater',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0820029,
    longitude: 14.4184171,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '83',
    name: 'Mucha Museum',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.084328,
    longitude: 14.4275632,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '84',
    name: 'Museum of Miniatures',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0872711,
    longitude: 14.3893891,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '85',
    name: 'Museum of Senses',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0839909,
    longitude: 14.4290515,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '86',
    name: 'Museum of Torture',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0871477,
    longitude: 14.4233583,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '87',
    name: 'Marionette Theatre',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.08604,
    longitude: 14.415832,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '88',
    name: 'Aircraft museum Prague-Kbely',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.125256,
    longitude: 14.535524,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '89',
    name: 'National Museum',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0790294,
    longitude: 14.4309259,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '90',
    name: 'National Gallery Prague – Kinsky Palace',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.087978,
    longitude: 14.4216398,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '91',
    name: 'Kafka Museum',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0883196,
    longitude: 14.4101432,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '92',
    name: 'Rudolfinum',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0899562,
    longitude: 14.4154393,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '93',
    name: 'Pilsner Urquell: The Original Beer Experience',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0840614,
    longitude: 14.4228199,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '94',
    name: 'The Army Museum Žižkov',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.CULTURE,
    latitude: 50.0875708,
    longitude: 14.4446676,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '95',
    name: 'Letná Beer Garden',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.FOOD,
    latitude: 50.0959571,
    longitude: 14.425651,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '96',
    name: 'Mincovna Restaurant',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.FOOD,
    latitude: 50.088296,
    longitude: 14.421273,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '97',
    name: 'U Červeného páva',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.FOOD,
    latitude: 50.086695,
    longitude: 14.422992,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '98',
    name: 'U Glaubiců Restaurant',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.FOOD,
    latitude: 50.087657,
    longitude: 14.403527,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '99',
    name: 'Pasáž Světozor',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.FOOD,
    latitude: 50.081852,
    longitude: 14.425,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '100',
    name: 'Medieval Tavern \"U Krále Brabantského\"',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.FOOD,
    latitude: 50.088976,
    longitude: 14.401552,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '101',
    name: 'Střídačka (The Hockey Bench)',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.FOOD,
    latitude: 50.088079,
    longitude: 14.422725,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '102',
    name: 'U Mecenáše Restaurant',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.FOOD,
    latitude: 50.087664,
    longitude: 14.402692,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '103',
    name: 'VNITROBLOCK',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.FOOD,
    latitude: 50.10194,
    longitude: 14.449328,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '104',
    name: 'Lokál Dlouhááá',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.FOOD,
    latitude: 50.0906931,
    longitude: 14.4257574,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '105',
    name: 'Ovocný Světozor',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.FOOD,
    latitude: 50.081833,
    longitude: 14.424955,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '106',
    name: 'Absintherie Jilská',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.FOOD,
    latitude: 50.0858292,
    longitude: 14.4189193,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '107',
    name: 'Dlouhá Street',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.NIGHTLIFE,
    latitude: 50.0902951,
    longitude: 14.4250176,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '108',
    name: 'Karlovy Lazne - Nightclub',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.NIGHTLIFE,
    latitude: 50.0855168,
    longitude: 14.4139501,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '109',
    name: 'SaSaZu Club',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.NIGHTLIFE,
    latitude: 50.0992876,
    longitude: 14.4447282,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '110',
    name: 'Anonymous Bar',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.NIGHTLIFE,
    latitude: 50.085353,
    longitude: 14.420081,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '111',
    name: 'Cross Club',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.NIGHTLIFE,
    latitude: 50.1082127,
    longitude: 14.4432664,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '112',
    name: 'Nebe Cocktail & Music Bar Celnice',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.NIGHTLIFE,
    latitude: 50.0881794,
    longitude: 14.4304937,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '113',
    name: 'The Pub Prague 1',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.NIGHTLIFE,
    latitude: 50.088003,
    longitude: 14.415943,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '114',
    name: 'Duplex',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.NIGHTLIFE,
    latitude: 50.0823675,
    longitude: 14.4266853,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '115',
    name: 'Roxy',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.NIGHTLIFE,
    latitude: 50.090689,
    longitude: 14.425874,
    images: ['place-3.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '116',
    name: 'Hemingway Bar',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.NIGHTLIFE,
    latitude: 50.0840083,
    longitude: 14.4142813,
    images: ['place-4.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '117',
    name: 'Lucerna Music Bar',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.NIGHTLIFE,
    latitude: 50.081353,
    longitude: 14.4254136,
    images: ['place-5.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '118',
    name: 'La Macumba Music Latino bar',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.NIGHTLIFE,
    latitude: 50.0726811,
    longitude: 14.403744,
    images: ['place-6.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '119',
    name: 'Prague Zoo',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.KIDS,
    latitude: 50.1167324,
    longitude: 14.4114195,
    images: ['place-7.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '120',
    name: 'Mirror Maze',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.KIDS,
    latitude: 50.0835029,
    longitude: 14.3963143,
    images: ['place-8.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '121',
    name: 'Lego Museum',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.KIDS,
    latitude: 50.0826241,
    longitude: 14.4193736,
    images: ['place-1.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
  {
    id: '122',
    name: 'Kingdom of Railways',
    shortDescription: '',
    description: '',
    practicalTips: '',
    category: PlaceCategory.KIDS,
    latitude: 50.0712712,
    longitude: 14.4026256,
    images: ['place-2.jpg'],
    estimatedVisitDuration: 60,
    priceRange: 'free',
    isPremium: false,
  },
];

export const seedDatabase = async (): Promise<void> => {
  const repo = new PlaceRepository();

  // Check if database is already seeded
  const existing = await repo.getAll();
  const now = new Date();
  
  if (existing.length > 0) {
    // Only update places that need updating (e.g., missing local images)
    // Check if any place needs updating by comparing images
    const placesToUpdate: Array<{ existing: Place; sample: typeof samplePlaces[0] }> = [];
    
    for (const existingPlace of existing) {
      const samplePlace = samplePlaces.find(p => p.id === existingPlace.id);
      if (samplePlace) {
        // Only update if images are different (e.g., if existing has URL instead of local file)
        const existingImages = existingPlace.images;
        const sampleImages = samplePlace.images;
        const needsUpdate = JSON.stringify(existingImages) !== JSON.stringify(sampleImages);
        
        if (needsUpdate) {
          placesToUpdate.push({ existing: existingPlace, sample: samplePlace });
        }
      }
    }
    
    // Batch update only places that need it
    for (const { existing: existingPlace, sample: samplePlace } of placesToUpdate) {
      await repo.update({
        ...samplePlace,
        createdAt: existingPlace.createdAt,
        updatedAt: now,
      });
    }
    
    // Insert any missing places
    for (const samplePlace of samplePlaces) {
      const exists = existing.find(p => p.id === samplePlace.id);
      if (!exists) {
        await repo.insert({
          ...samplePlace,
          createdAt: now,
          updatedAt: now,
        });
      }
    }
  } else {
    // Insert sample places if database is empty
    for (const place of samplePlaces) {
      await repo.insert({
        ...place,
        createdAt: now,
        updatedAt: now,
      });
    }
  }

  // Seed tours
  await seedTours();

  // Seed hotels
  await seedHotels();

  // Seed practical tips
  await seedTips();

  // Seed itineraries
  await seedItineraries();
};

const sampleTours: Omit<Tour, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'tour-1',
    title: 'Prague Castle: Skip-the-Line Ticket & Audio Guide',
    shortDescription: 'Skip the long queues and explore Prague Castle at your own pace with an audio guide',
    description: 'Visit the largest ancient castle complex in the world without waiting in long lines. This skip-the-line ticket includes access to all major attractions within Prague Castle, including St. Vitus Cathedral, Old Royal Palace, St. George\'s Basilica, and Golden Lane. The audio guide provides fascinating insights into the history and architecture of this UNESCO World Heritage site.',
    duration: '2-3 hours',
    priceRange: '€15-25',
    affiliateLink: 'https://www.getyourguide.com/prague-l10/prague-castle-skip-the-line-ticket-with-audio-guide-t26944/',
    provider: 'GetYourGuide',
    category: 'Sightseeing',
    rating: 4.6,
    requiresOnline: true,
  },
  {
    id: 'tour-2',
    title: 'Prague: Vltava River Cruise with Buffet Lunch',
    shortDescription: 'Enjoy a relaxing cruise along the Vltava River with delicious buffet lunch',
    description: 'Experience Prague from a unique perspective on a scenic river cruise. Sail past iconic landmarks including Charles Bridge, Prague Castle, and the National Theatre while enjoying a delicious buffet lunch. The cruise offers stunning views of the city\'s architecture and is perfect for photography enthusiasts. Available in multiple languages.',
    duration: '2 hours',
    priceRange: '€30-45',
    affiliateLink: 'https://www.getyourguide.com/prague-l10/prague-vltava-river-cruise-with-buffet-lunch-t22328/',
    provider: 'GetYourGuide',
    category: 'Cruise',
    rating: 4.5,
    requiresOnline: true,
  },
  {
    id: 'tour-3',
    title: 'Prague: Old Town & Jewish Quarter Walking Tour',
    shortDescription: 'Discover the historic Old Town and Jewish Quarter with a knowledgeable local guide',
    description: 'Explore Prague\'s most historic neighborhoods on this comprehensive walking tour. Visit the Old Town Square with its famous Astronomical Clock, walk through the narrow streets of the Jewish Quarter, and learn about the rich history of Prague\'s Jewish community. The tour includes entry to the Old-New Synagogue and the Jewish Cemetery. Perfect for first-time visitors.',
    duration: '3 hours',
    priceRange: '€20-30',
    affiliateLink: 'https://www.getyourguide.com/prague-l10/prague-old-town-jewish-quarter-walking-tour-t3573/',
    provider: 'GetYourGuide',
    category: 'Walking Tour',
    rating: 4.7,
    requiresOnline: true,
  },
  {
    id: 'tour-4',
    title: 'Prague: Evening Vltava River Cruise with Dinner',
    shortDescription: 'Romantic evening cruise with dinner and live music',
    description: 'Experience Prague\'s magical atmosphere on an evening river cruise. Enjoy a delicious 3-course dinner while sailing past beautifully illuminated landmarks. The cruise includes live music and offers breathtaking views of Prague Castle, Charles Bridge, and the city skyline at sunset. A perfect romantic experience for couples.',
    duration: '2.5 hours',
    priceRange: '€50-70',
    affiliateLink: 'https://www.getyourguide.com/prague-l10/prague-evening-vltava-river-cruise-with-dinner-t22330/',
    provider: 'GetYourGuide',
    category: 'Dinner Cruise',
    rating: 4.6,
    requiresOnline: true,
  },
  {
    id: 'tour-5',
    title: 'Prague: Food Tour with Traditional Czech Dishes',
    shortDescription: 'Taste authentic Czech cuisine at local restaurants and pubs',
    description: 'Discover the flavors of Czech cuisine on this guided food tour. Visit traditional restaurants and pubs in the Old Town, sample classic dishes like goulash, dumplings, and schnitzel, and learn about Czech culinary traditions. The tour includes multiple food stops and drinks. A must-do for food lovers visiting Prague.',
    duration: '3.5 hours',
    priceRange: '€45-65',
    affiliateLink: 'https://www.getyourguide.com/prague-l10/prague-food-tour-with-traditional-czech-dishes-t3575/',
    provider: 'GetYourGuide',
    category: 'Food Tour',
    rating: 4.8,
    requiresOnline: true,
  },
  {
    id: 'tour-6',
    title: 'Prague: Ghosts and Legends of Old Town Walking Tour',
    shortDescription: 'Explore Prague\'s dark history and spooky legends on an evening walking tour',
    description: 'Discover the mysterious side of Prague on this atmospheric evening walking tour. Hear spine-chilling stories about ghosts, alchemists, and legends as you walk through the dimly lit streets of the Old Town. Visit haunted locations and learn about Prague\'s dark history. Perfect for those who enjoy spooky stories and want to see a different side of the city.',
    duration: '1.5 hours',
    priceRange: '€15-25',
    affiliateLink: 'https://www.getyourguide.com/prague-l10/prague-ghosts-and-legends-of-old-town-walking-tour-t3576/',
    provider: 'GetYourGuide',
    category: 'Walking Tour',
    rating: 4.5,
    requiresOnline: true,
  },
  {
    id: 'tour-7',
    title: 'Prague: Day Trip to Český Krumlov',
    shortDescription: 'Visit the fairy-tale town of Český Krumlov on a day trip from Prague',
    description: 'Escape the city and visit one of the most beautiful towns in the Czech Republic. Český Krumlov is a UNESCO World Heritage site with a stunning castle, charming medieval streets, and picturesque river views. The tour includes transportation, a guided walking tour, and free time to explore. Perfect for those who want to see more of the Czech Republic.',
    duration: '10 hours',
    priceRange: '€50-80',
    affiliateLink: 'https://www.getyourguide.com/prague-l10/prague-day-trip-to-cesky-krumlov-t3577/',
    provider: 'GetYourGuide',
    category: 'Day Trip',
    rating: 4.7,
    requiresOnline: true,
  },
  {
    id: 'tour-8',
    title: 'Prague: Beer Tasting Tour in Traditional Pubs',
    shortDescription: 'Sample the best Czech beers at traditional pubs with a local guide',
    description: 'Experience Czech beer culture on this guided tasting tour. Visit traditional pubs and breweries, sample different types of Czech beer, and learn about the brewing process and history. The tour includes multiple beer tastings and snacks. A must-do for beer enthusiasts visiting Prague.',
    duration: '3 hours',
    priceRange: '€35-50',
    affiliateLink: 'https://www.getyourguide.com/prague-l10/prague-beer-tasting-tour-in-traditional-pubs-t3578/',
    provider: 'GetYourGuide',
    category: 'Beer Tour',
    rating: 4.6,
    requiresOnline: true,
  },
  {
    id: 'tour-9',
    title: 'Prague: Segway Tour of Old Town and Castle',
    shortDescription: 'Explore Prague on a fun Segway tour covering major attractions',
    description: 'Discover Prague in a fun and unique way on a Segway tour. Glide through the Old Town, cross Charles Bridge, and explore the area around Prague Castle. The tour includes training, safety equipment, and a knowledgeable guide. Perfect for those who want to cover more ground while having fun.',
    duration: '2.5 hours',
    priceRange: '€50-70',
    affiliateLink: 'https://www.getyourguide.com/prague-l10/prague-segway-tour-of-old-town-and-castle-t3579/',
    provider: 'GetYourGuide',
    category: 'Segway Tour',
    rating: 4.4,
    requiresOnline: true,
  },
  {
    id: 'tour-10',
    title: 'Prague: Astronomical Clock Tower Entry Ticket',
    shortDescription: 'Skip the line and climb the Astronomical Clock Tower for panoramic views',
    description: 'Visit one of Prague\'s most iconic landmarks without waiting in long queues. Climb the Astronomical Clock Tower for breathtaking panoramic views of the Old Town Square and surrounding areas. The ticket includes access to the tower and an audio guide explaining the history of the clock. Perfect for photography enthusiasts.',
    duration: '30-45 minutes',
    priceRange: '€10-15',
    affiliateLink: 'https://www.getyourguide.com/prague-l10/prague-astronomical-clock-tower-entry-ticket-t3580/',
    provider: 'GetYourGuide',
    category: 'Sightseeing',
    rating: 4.5,
    requiresOnline: true,
  },
];

export const seedTours = async (): Promise<void> => {
  const repo = new TourRepository();
  const existing = await repo.getAll();
  const now = new Date();

  if (existing.length > 0) {
    // Only insert missing tours, skip updates if data already exists
    for (const sampleTour of sampleTours) {
      const exists = existing.find((t) => t.id === sampleTour.id);
      if (!exists) {
        await repo.insert({
          ...sampleTour,
          createdAt: now,
          updatedAt: now,
        });
      }
    }
    return;
  }

  // Insert sample tours if database is empty
  for (const tour of sampleTours) {
    await repo.insert({
      ...tour,
      createdAt: now,
      updatedAt: now,
    });
  }
};

const sampleHotels: Omit<Hotel, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'hotel-1',
    name: 'Metropolitan Old Town',
    area: 'Old Town',
    description: 'Elegant hotel in the heart of Old Town, just steps away from major landmarks. Features modern rooms with historic charm, rooftop terrace with city views, and excellent location for sightseeing.',
    priceRange: '€100-150',
    affiliateLink: 'https://www.booking.com/hotel/cz/rubicon-old-town.en.html?aid=1709572',
    rating: 4.5,
    features: ['Rooftop terrace', 'City center location', 'Historic building', 'Free WiFi'],
  },
  {
    id: 'hotel-2',
    name: 'River View Residence by Charles Bridge',
    area: 'Lesser Town',
    description: 'Beautiful apartment hotel with stunning views of Charles Bridge and Vltava River. Perfect for couples seeking a romantic stay with river views and easy access to Prague Castle.',
    priceRange: '€120-180',
    affiliateLink: 'https://www.booking.com/hotel/cz/river-view-residence-by-charles-bridge.en.html?aid=1709572',
    rating: 4.7,
    features: ['River view', 'Charles Bridge views', 'Apartment style', 'Kitchen facilities'],
  },
  {
    id: 'hotel-3',
    name: 'Dancing House Hotel',
    area: 'New Town',
    description: 'Iconic modern hotel in the famous Dancing House building. Unique architecture, contemporary design, and excellent views of the river and city. Perfect for architecture enthusiasts.',
    priceRange: '€150-250',
    affiliateLink: 'https://www.booking.com/hotel/cz/dancing-house.en.html?aid=1709572',
    rating: 4.6,
    features: ['Iconic architecture', 'Rooftop bar', 'Modern design', 'River views'],
  },
  {
    id: 'hotel-4',
    name: 'Pension Akát',
    area: 'Žižkov',
    description: 'Budget-friendly pension in the vibrant Žižkov district. Clean, comfortable rooms, friendly staff, and great value for money. Close to nightlife and local restaurants.',
    priceRange: '€40-70',
    affiliateLink: 'https://www.booking.com/hotel/cz/pension-aka-t.en.html?aid=1709572',
    rating: 4.2,
    features: ['Budget friendly', 'Local area', 'Good value', 'Public transport nearby'],
  },
  {
    id: 'hotel-5',
    name: 'Czech Inn',
    area: 'Žižkov',
    description: 'Modern hostel-hotel hybrid offering both private rooms and dormitories. Great for budget travelers and backpackers. Located in the lively Žižkov neighborhood with excellent nightlife.',
    priceRange: '€30-60',
    affiliateLink: 'https://www.booking.com/hotel/cz/czech-inn.en.html?aid=1709572',
    rating: 4.3,
    features: ['Budget option', 'Hostel & hotel', 'Social atmosphere', 'Nightlife nearby'],
  },
  {
    id: 'hotel-6',
    name: 'Wenceslas Square Hotel',
    area: 'New Town',
    description: 'Hotel with rooftop terrace overlooking Wenceslas Square. Central location, modern rooms, and excellent views of the famous square. Great for first-time visitors.',
    priceRange: '€80-130',
    affiliateLink: 'https://www.booking.com/hotel/cz/wenceslas-square.en.html?aid=1709572',
    rating: 4.4,
    features: ['Rooftop terrace', 'Wenceslas Square views', 'Central location', 'Shopping nearby'],
  },
  {
    id: 'hotel-7',
    name: 'Hotel Orion',
    area: 'Vinohrady',
    description: 'Charming hotel in the peaceful Vinohrady district, surrounded by parks and cafés. Perfect for longer stays, families, and those seeking a relaxed atmosphere away from tourist crowds.',
    priceRange: '€70-110',
    affiliateLink: 'https://www.booking.com/hotel/cz/orion-prague-2.en.html?aid=1709572',
    rating: 4.5,
    features: ['Parks nearby', 'Café culture', 'Quiet area', 'Family friendly'],
  },
  {
    id: 'hotel-8',
    name: 'Anna Hotel',
    area: 'Vinohrady',
    description: 'Boutique hotel in Vinohrady with elegant design and personalized service. Close to Riegrovy Sady park, excellent cafés, and local restaurants. Ideal for a relaxed stay.',
    priceRange: '€90-140',
    affiliateLink: 'https://www.booking.com/hotel/cz/anna.en.html?aid=1709572',
    rating: 4.6,
    features: ['Boutique style', 'Parks nearby', 'Local cafés', 'Personalized service'],
  },
  {
    id: 'hotel-9',
    name: 'Libero Residence',
    area: 'Vinohrady',
    description: 'Apartment hotel in the green Vinohrady district. Spacious apartments with kitchen facilities, perfect for families and longer stays. Surrounded by parks and excellent dining options.',
    priceRange: '€100-160',
    affiliateLink: 'https://www.booking.com/hotel/cz/pension44praha.en.html?aid=1709572',
    rating: 4.5,
    features: ['Apartment style', 'Kitchen facilities', 'Family friendly', 'Parks nearby'],
  },
  {
    id: 'hotel-10',
    name: 'Grand Hotel Bohemia',
    area: 'Old Town',
    description: 'Luxury 5-star hotel in the heart of Old Town. Elegant rooms, fine dining restaurant, spa facilities, and impeccable service. Perfect for a luxurious stay in Prague.',
    priceRange: '€200-350',
    affiliateLink: 'https://www.booking.com/hotel/cz/grandhotelbohemia.en.html?aid=1709572',
    rating: 4.8,
    features: ['5-star luxury', 'Spa facilities', 'Fine dining', 'Historic building', 'Premium service'],
  },
  {
    id: 'hotel-11',
    name: 'Alchymist Grand Hotel & Spa',
    area: 'Lesser Town',
    description: 'Luxurious hotel in Lesser Town with baroque architecture and spa facilities. Romantic atmosphere, elegant rooms, and excellent location near Prague Castle. Perfect for couples.',
    priceRange: '€180-300',
    affiliateLink: 'https://www.booking.com/hotel/cz/reshotelalchymistprague.en.html?aid=1709572',
    rating: 4.7,
    features: ['Luxury spa', 'Baroque architecture', 'Romantic', 'Prague Castle nearby', 'Fine dining'],
  },
  {
    id: 'hotel-12',
    name: 'KINGS COURT',
    area: 'Old Town',
    description: 'Premium hotel in Old Town with elegant design and excellent service. Central location, spacious rooms, and attention to detail. Perfect for discerning travelers.',
    priceRange: '€150-280',
    affiliateLink: 'https://booking.stay22.com/czechtheworld/QiazfhbDc-',
    rating: 4.6,
    features: ['Premium service', 'Central location', 'Elegant design', 'Spacious rooms'],
  },
];

export const seedHotels = async (): Promise<void> => {
  const repo = new HotelRepository();
  const existing = await repo.getAll();
  const now = new Date();

  if (existing.length > 0) {
    // Only insert missing hotels, skip updates if data already exists
    for (const sampleHotel of sampleHotels) {
      const exists = existing.find((h) => h.id === sampleHotel.id);
      if (!exists) {
        await repo.insert({
          ...sampleHotel,
          createdAt: now,
          updatedAt: now,
        } as Hotel & { createdAt: Date; updatedAt: Date });
      }
    }
    return;
  }

  // Insert sample hotels if database is empty
  for (const hotel of sampleHotels) {
    await repo.insert({
      ...hotel,
      createdAt: now,
      updatedAt: now,
    } as Hotel & { createdAt: Date; updatedAt: Date });
  }
};

const sampleTips: Omit<PracticalTip, 'updatedAt'>[] = [
  // TRANSPORT tips
  {
    id: 'tip-transport-1',
    category: TipCategory.TRANSPORT,
    title: 'Prague Public Transport System',
    content: 'Prague has an excellent public transport system with metro, trams, and buses. The system is ranked among the best in the world. You can buy tickets at ticket machines, via the PID Lítačka mobile app, or at tobacco shops. Always validate your ticket when entering - you only need to validate once per journey, even when transferring between lines.',
    icon: 'subway',
    priority: 10,
  },
  {
    id: 'tip-transport-2',
    category: TipCategory.TRANSPORT,
    title: 'Ticket Types and Prices',
    content: 'Short-term tickets: 30 minutes (30 CZK), 90 minutes (40 CZK), 24 hours (120 CZK), 72 hours (330 CZK). For longer stays, consider a monthly pass. Children under 6 travel free, children 6-15 and seniors 65+ get discounted tickets. Always validate your ticket immediately after purchase - fines for traveling without a valid ticket are 1000 CZK.',
    icon: 'ticket',
    priority: 9,
  },
  {
    id: 'tip-transport-3',
    category: TipCategory.TRANSPORT,
    title: 'From Airport to City Center',
    content: 'The cheapest way: Take bus 100 or 119 to metro station, then metro to city center (total 40 CZK). Bus 100 goes to Zličín (metro B), bus 119 goes to Nádraží Veleslavín (metro A). Journey time: 30-45 minutes. Alternatively, Airport Express bus (100 CZK) goes directly to main train station. Taxi/Uber costs 400-600 CZK.',
    icon: 'airplane',
    priority: 10,
  },
  {
    id: 'tip-transport-4',
    category: TipCategory.TRANSPORT,
    title: 'Using Metro in Prague',
    content: 'Prague has 3 metro lines (A, B, C) with clear color coding. Metro runs from 5 AM to midnight (extended hours on weekends). Transfer stations are well-marked and transfers usually take just a few minutes. During rush hours (7-9 AM, 4-6 PM), metro can be very crowded. Avoid traveling with large luggage during peak times.',
    icon: 'train',
    priority: 8,
  },
  {
    id: 'tip-transport-5',
    category: TipCategory.TRANSPORT,
    title: 'Trams - Scenic Way to Travel',
    content: 'Trams are a great way to see the city while traveling. Popular routes include tram 22 (passes many major attractions) and tram 17. Trams run frequently, usually every 5-10 minutes during the day. Remember to press the stop button before your stop. Trams are accessible and safe, but watch your belongings during rush hours.',
    icon: 'car',
    priority: 7,
  },
  {
    id: 'tip-transport-6',
    category: TipCategory.TRANSPORT,
    title: 'Finding Your Way',
    content: 'Download the official PID Lítačka app for route planning, real-time schedules, and mobile tickets. Google Maps also works well for public transport in Prague. At metro stations and major tram stops, you\'ll find route maps and schedules. Most locals are happy to help if you ask for directions.',
    icon: 'map',
    priority: 6,
  },
  
  // MONEY tips
  {
    id: 'tip-money-1',
    category: TipCategory.MONEY,
    title: 'Czech Currency - Czech Crown (CZK)',
    content: 'The official currency is the Czech Crown (Koruna česká, CZK). Czech Republic is not in the Eurozone. Most places accept cards, but always carry some cash for smaller shops, markets, and tips. Current exchange rate: approximately 1 EUR = 24-25 CZK, 1 USD = 22-23 CZK (rates vary).',
    icon: 'cash',
    priority: 10,
  },
  {
    id: 'tip-money-2',
    category: TipCategory.MONEY,
    title: 'Currency Exchange - Avoid Tourist Traps',
    content: 'NEVER exchange money at exchange offices in tourist areas (Old Town Square, Wenceslas Square) - they offer terrible rates and hidden fees. Use ATMs instead (they offer fair rates) or exchange at banks. Good exchange offices include: Exchange.cz, Interchange, or banks. Always check the rate and commission before exchanging. Avoid "0% commission" signs - they hide fees in the exchange rate.',
    icon: 'card',
    priority: 10,
  },
  {
    id: 'tip-money-3',
    category: TipCategory.MONEY,
    title: 'Daily Budget Guide',
    content: 'Budget traveler: 800-1200 CZK/day (hostel, street food, free attractions). Mid-range: 1500-2500 CZK/day (hotel, restaurants, paid attractions). Luxury: 3000+ CZK/day. Meal costs: Budget restaurant 150-250 CZK, Mid-range 300-500 CZK, Fine dining 600+ CZK. Beer: 40-60 CZK in pubs, 80-120 CZK in tourist areas.',
    icon: 'wallet',
    priority: 8,
  },
  {
    id: 'tip-money-4',
    category: TipCategory.MONEY,
    title: 'Paying with Cards',
    content: 'Most restaurants, shops, and hotels accept credit/debit cards (Visa, Mastercard). Contactless payments are very common. However, some smaller shops, markets, and street vendors only accept cash. Always ask before ordering if you\'re not sure. Tipping is usually done in cash even when paying by card.',
    icon: 'card-outline',
    priority: 7,
  },
  
  // SAFETY tips
  {
    id: 'tip-safety-1',
    category: TipCategory.SAFETY,
    title: 'Prague is Generally Very Safe',
    content: 'Prague is one of the safest cities in Europe. Violent crime is extremely rare. However, like in any major tourist destination, be aware of pickpockets, especially in crowded areas like Charles Bridge, Old Town Square, and on public transport. Keep valuables secure and be cautious of your surroundings.',
    icon: 'shield-checkmark',
    priority: 9,
  },
  {
    id: 'tip-safety-2',
    category: TipCategory.SAFETY,
    title: 'Common Tourist Scams to Avoid',
    content: '1) Fake money exchange offices with terrible rates. 2) Taxi drivers overcharging (use Uber/Bolt or official taxis). 3) Pickpockets in crowded areas. 4) "Free" tours that demand payment. 5) People offering to help with tickets then asking for money. 6) Fake police asking to check your wallet. 7) Restaurant menu scams (check prices before ordering). Always trust your instincts and walk away from suspicious situations.',
    icon: 'warning',
    priority: 10,
  },
  {
    id: 'tip-safety-3',
    category: TipCategory.SAFETY,
    title: 'Protecting Your Belongings',
    content: 'Keep wallets and phones in front pockets or secure bags. Don\'t leave bags unattended. Be extra careful on trams and metro, especially during rush hours. Avoid displaying expensive jewelry or large amounts of cash. Use hotel safes for passports and extra money. Make copies of important documents and store them separately.',
    icon: 'lock-closed',
    priority: 8,
  },
  {
    id: 'tip-safety-4',
    category: TipCategory.SAFETY,
    title: 'Safe Areas and Areas to Be Cautious',
    content: 'Prague is generally safe throughout, but be extra cautious in: Very crowded tourist areas (pickpockets), late-night areas around train stations, and isolated areas after dark. Safe areas include: Old Town, Lesser Town, Vinohrady, and most residential districts. Trust your instincts - if an area feels unsafe, leave.',
    icon: 'location',
    priority: 6,
  },
  
  // EMERGENCY tips
  {
    id: 'tip-emergency-1',
    category: TipCategory.EMERGENCY,
    title: 'Emergency Phone Numbers',
    content: '112 - European emergency number (police, fire, ambulance). 158 - Police. 150 - Fire department. 155 - Ambulance. 156 - Municipal police. For non-emergency medical issues, visit a pharmacy (lékárna) or call your embassy. EU citizens can use their European Health Insurance Card (EHIC) for emergency treatment.',
    icon: 'call',
    priority: 10,
  },
  {
    id: 'tip-emergency-2',
    category: TipCategory.EMERGENCY,
    title: 'Lost or Stolen Items',
    content: 'If something is stolen, report it to police (158) immediately. For lost items on public transport, contact Prague Public Transport lost & found. For lost passports, contact your embassy immediately. Keep embassy contact information with you. Travel insurance is highly recommended to cover theft, loss, and medical emergencies.',
    icon: 'document-text',
    priority: 8,
  },
  {
    id: 'tip-emergency-3',
    category: TipCategory.EMERGENCY,
    title: 'Medical Emergencies',
    content: 'For serious emergencies, call 155 (ambulance) or 112. Major hospitals with 24/7 emergency departments include: General University Hospital (VFN), Motol University Hospital. Pharmacies (lékárna) are widely available - look for green cross signs. Many pharmacies are open 24/7. EU citizens should carry EHIC card.',
    icon: 'medical',
    priority: 9,
  },
  
  // TIPPING tips
  {
    id: 'tip-tipping-1',
    category: TipCategory.TIPPING,
    title: 'Tipping in Restaurants',
    content: 'Tipping is customary but not mandatory. Standard tip: 10-15% of the bill, or round up to the nearest 50 or 100 CZK. For excellent service, 15-20% is appreciated. Tips are usually given in cash, even when paying by card. Simply tell the server the total amount you want to pay (including tip) when paying by card, or leave cash on the table.',
    icon: 'restaurant',
    priority: 10,
  },
  {
    id: 'tip-tipping-2',
    category: TipCategory.TIPPING,
    title: 'Tipping in Other Places',
    content: 'Cafés: Round up or 10-20 CZK. Bars: 10-20 CZK per drink or 10% of bill. Taxis: Round up to nearest 10 CZK or 10%. Tour guides: 100-200 CZK per person for half-day tours, 200-500 CZK for full-day tours. Hotel staff: 50-100 CZK for porters, 50-100 CZK per night for housekeeping (left in room).',
    icon: 'card',
    priority: 8,
  },
  {
    id: 'tip-tipping-3',
    category: TipCategory.TIPPING,
    title: 'When Not to Tip',
    content: 'You don\'t need to tip: Fast food restaurants, self-service places, when service charge is already included (check your bill), or if service was poor. Tipping is a gesture of appreciation for good service, not an obligation. If you\'re unsure, observe what locals do or simply round up the bill.',
    icon: 'close-circle',
    priority: 6,
  },
  
  // INTERNET tips
  {
    id: 'tip-internet-1',
    category: TipCategory.INTERNET,
    title: 'Free WiFi in Prague',
    content: 'Free WiFi is widely available in Prague. Most cafés, restaurants, hotels, and public spaces offer free WiFi. Look for networks named "Prague WiFi" in public areas. Many tourist attractions also provide free WiFi. However, be cautious when using public WiFi - avoid accessing sensitive information like banking. Consider using a VPN for added security.',
    icon: 'wifi',
    priority: 9,
  },
  {
    id: 'tip-internet-2',
    category: TipCategory.INTERNET,
    title: 'Mobile Data and SIM Cards',
    content: 'EU roaming: If you have an EU SIM card, you can use your data plan in Czech Republic without extra charges (fair use policy applies). For non-EU visitors, consider buying a local SIM card. Major providers: Vodafone, T-Mobile, O2. Prepaid SIM cards cost around 200-300 CZK and include data. You can buy them at airports, train stations, or provider stores.',
    icon: 'phone-portrait',
    priority: 7,
  },
  
  // GENERAL tips
  {
    id: 'tip-general-1',
    category: TipCategory.GENERAL,
    title: 'Best Time to Visit Prague',
    content: 'Spring (April-May) and Fall (September-October): Best weather, fewer crowds, moderate prices. Summer (June-August): Warm weather but very crowded and higher prices. Winter (December-February): Cold but magical with Christmas markets, fewer tourists, lower prices. January-February: Least crowded but coldest. Avoid major holidays and school breaks for fewer crowds.',
    icon: 'calendar',
    priority: 9,
  },
  {
    id: 'tip-general-2',
    category: TipCategory.GENERAL,
    title: 'Avoiding Crowds',
    content: 'Visit major attractions early morning (before 8 AM) or late evening. Charles Bridge is almost empty at sunrise. Visit popular sites on weekdays rather than weekends. Consider visiting in shoulder seasons (April-May, September-October). Stay in neighborhoods like Vinohrady or Žižkov - just 10 minutes from center but much quieter. Book tickets online in advance to skip queues.',
    icon: 'people',
    priority: 8,
  },
  {
    id: 'tip-general-3',
    category: TipCategory.GENERAL,
    title: 'Tap Water is Safe to Drink',
    content: 'Tap water in Prague is safe to drink and of high quality. You can drink tap water everywhere - in restaurants, hotels, and public fountains. This will save you money and reduce plastic waste. Bring a reusable water bottle and refill it throughout the day. Many public places have drinking fountains.',
    icon: 'water',
    priority: 8,
  },
  {
    id: 'tip-general-4',
    category: TipCategory.GENERAL,
    title: 'Basic Czech Phrases',
    content: 'Hello: Dobrý den (DOH-bree den). Thank you: Děkuji (DYE-koo-yee). Please: Prosím (PRO-seem). Yes: Ano (AH-no). No: Ne (NEH). Excuse me: Promiňte (PRO-min-tyeh). Do you speak English?: Mluvíte anglicky? (MLU-vee-teh an-GLIT-skee). While most people in tourist areas speak English, locals appreciate when you try Czech phrases.',
    icon: 'chatbubbles',
    priority: 7,
  },
  {
    id: 'tip-general-5',
    category: TipCategory.GENERAL,
    title: 'Language in Prague',
    content: 'Czech is the official language, but English is widely spoken in tourist areas, hotels, restaurants, and by younger people. You\'ll have no problem getting by with English in Prague. However, learning a few basic Czech phrases (hello, thank you, please) is appreciated by locals and shows respect for the culture.',
    icon: 'language',
    priority: 6,
  },
  {
    id: 'tip-general-6',
    category: TipCategory.GENERAL,
    title: 'Alcohol Laws',
    content: 'Legal drinking age is 18. Drinking in public is generally tolerated in parks and some public spaces, but be respectful. Drinking on public transport is prohibited. Some areas have specific restrictions. Don\'t drink and drive - zero tolerance policy. Beer is very cheap and part of Czech culture, but drink responsibly.',
    icon: 'beer',
    priority: 5,
  },
  {
    id: 'tip-general-7',
    category: TipCategory.GENERAL,
    title: 'Shopping Tips',
    content: 'Most shops are open Monday-Friday 9 AM-6 PM, Saturday 9 AM-1 PM, closed Sundays. Large shopping centers are open daily including Sundays. Tourist shops in Old Town are open daily but more expensive. For better prices, shop away from main tourist areas. Czech crystal, garnet jewelry, and marionettes are popular souvenirs.',
    icon: 'bag',
    priority: 5,
  },
  {
    id: 'tip-general-8',
    category: TipCategory.GENERAL,
    title: 'Dress Code and What to Pack',
    content: 'Prague is casual - no strict dress codes. Comfortable walking shoes are essential (cobblestone streets!). Weather can change quickly - pack layers. In summer: light clothes, sunscreen, hat. In winter: warm coat, gloves, hat, waterproof boots. Umbrella is useful year-round. For churches, cover shoulders and knees (scarves available at entrances).',
    icon: 'shirt',
    priority: 6,
  },
];

export const seedTips = async (): Promise<void> => {
  const repo = new TipRepository();
  const existing = await repo.getAll();
  const now = new Date();

  if (existing.length > 0) {
    // Only insert missing tips, skip updates if data already exists
    for (const sampleTip of sampleTips) {
      const exists = existing.find((t) => t.id === sampleTip.id);
      if (!exists) {
        await repo.insert({
          ...sampleTip,
          updatedAt: now,
        });
      }
    }
    return;
  }

  // Insert sample tips if database is empty
  for (const tip of sampleTips) {
    await repo.insert({
      ...tip,
      updatedAt: now,
    });
  }
};

const sampleItineraries: Omit<Itinerary, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'itinerary-1-day',
    title: '1 Day in Prague: Best of Prague in 24 Hours',
    description: 'Experience the best of Prague in just 24 hours! This carefully crafted itinerary takes you through the city\'s most iconic landmarks, starting at Prague Castle and descending through Lesser Town, across Charles Bridge, and into the historic Old Town. Designed by locals who know every corner of this enchanting city, this route maximizes your time while minimizing walking distance. The route is designed so you can see as much as possible in one day and also save elevation, as it starts up at the Castle and you gradually descend to the river and into the Old Town. Perfect for first-time visitors who want to see the must-see spots without rushing.',
    type: ItineraryType.ONE_DAY,
    theme: ItineraryTheme.FIRST_TIME,
    places: [
      {
        placeId: '2', // Prague Castle
        order: 1,
        estimatedDuration: 120,
        transportTime: 0,
        transportMode: TransportMode.WALKING,
        notes: 'START HERE: You have two options - Malostranská metro/tram station (closer but requires stairs) or Pražský Hrad tram station (further but no stairs). Entrance to the Castle Complex is FREE. For interiors, tickets are around 250 CZK. Castle area open 6 AM-10 PM, buildings 9 AM-5 PM. Don\'t miss: St. Vitus Cathedral (Gothic masterpiece), St. George\'s Basilica (Romanesque church), Golden Lane (colorful houses, best in morning), Changing of the Guard (every hour, grand ceremony at noon), and the panoramic view from Hradčanské Square.',
      },
      {
        placeId: '4', // Petřín Hill (optional detour B)
        order: 2,
        estimatedDuration: 90,
        transportTime: 15,
        transportMode: TransportMode.WALKING,
        notes: 'OPTIONAL DETOUR B: Beautiful but optional. If you prefer a relaxed day, skip this and continue to Lesser Town. Route: From Hradčanské náměstí via Úvoz Street to Strahov Monastery (oldest Premonstratensian monastery, beautiful library), then to Petřín Tower (220 CZK, elevator extra fee - 1:5 scale replica of Eiffel Tower). Walk down through Petřín orchards (steep but beautiful) or take the funicular (60 CZK). Continue to Church of Our Lady Victorious (Infant Jesus of Prague) and then to Lesser Town Square.',
      },
      {
        placeId: '6', // John Lennon Wall
        order: 3,
        estimatedDuration: 15,
        transportTime: 10,
        transportMode: TransportMode.WALKING,
        notes: 'Located at Velkopřevorské náměstí, hidden by the side of the royal road. Symbol of peace, love, and artistic freedom. Originally a regular wall, it became a canvas for political dissent during Communist era. After John Lennon\'s assassination in 1980, it transformed into a tribute. The wall is continually changing with new graffiti and messages. Free to visit. Nearby: Velkopřevorský mlýn (Grand Priory Mill) at Čertovka Canal - one of the last remaining functional water mills in Prague.',
      },
      {
        placeId: '1', // Charles Bridge
        order: 4,
        estimatedDuration: 30,
        transportTime: 5,
        transportMode: TransportMode.WALKING,
        notes: 'The most famous sight of Prague! Stone Gothic bridge spanning the Vltava River with 16 arches and 30 statues of saints. Built in 1357 by King Charles IV. Visit early morning (before 8 AM) or late evening to avoid crowds. Don\'t miss: Statue of St. John of Nepomuk - rub the bronze plaque for good luck and to ensure you return to Prague! After crossing, turn 2x right to see the famous view from Bedřich Smetana statue - one of the best Instagram spots that most tourists miss.',
      },
      {
        placeId: '3', // Old Town Square
        order: 5,
        estimatedDuration: 90,
        transportTime: 10,
        transportMode: TransportMode.WALKING,
        notes: 'The historical heart of Prague! Must-see attractions: Astronomical Clock (oldest in world, show every hour 9 AM-11 PM - "Walk of the Apostles"), Old Town Hall tower (300 CZK, incredible panoramic views), 27 crosses on the ground (memorial to 27 executed leaders from 1621), St. Nicholas Church (Baroque, organ played by Mozart), Marian Column (reconstructed in 2020), and Church of Our Lady before Týn (Gothic masterpiece with twin 80m spires). Lunch recommendations: Mincovna (great daily menus), U Červeného Páva, or Střídačka (owned by Czech hockey players, 2 meal options daily).',
      },
    ],
    estimatedDuration: 1440, // 24 hours in minutes
    walkingDistance: 5.5, // approximately 5.5 km for main route
    transportHints: [
      'START: Malostranská metro/tram station (Line A, closer but requires stairs) OR Pražský Hrad tram station (tram 22, further but no stairs)',
      'The route is designed to descend from the Castle, saving elevation - you start high and walk downhill',
      'Most of the route is walkable - public transport mainly needed to reach starting point',
      'Consider 24-hour public transport ticket (120 CZK) if you plan to use metro/tram',
      'END: Wenceslas Square (Václavské náměstí) at Muzeum metro station',
      'From end point: 1 metro stop to Main Train Station (Hlavní nádraží), 2 stops to Florenc bus station, or continue to airport via green metro to Nádraží Veleslavín then bus 119',
      'OPTIONAL DETOUR C - Jewish Quarter: Between Old Town Square and Vltava River. Must-see: Old-New Synagogue (oldest active in Europe, 13th century), Old Jewish Cemetery (15th century), Jewish Museum, Klausen Synagogue, Spanish Synagogue. Add 60-90 minutes if visiting.',
      'After Old Town Square: Continue via Celetná Street to Powder Tower (Gothic gate, gunpowder storage) and Municipal House (Art Nouveau, 1912, guided tours available), then to Wenceslas Square',
    ],
    difficulty: Difficulty.MODERATE,
    isPremium: false,
  },
];

export const seedItineraries = async (): Promise<void> => {
  const repo = new ItineraryRepository();
  const existing = await repo.getAll();
  const now = new Date();

  if (existing.length > 0) {
    // Only insert missing itineraries, skip updates if data already exists
    for (const sampleItinerary of sampleItineraries) {
      const exists = existing.find((i) => i.id === sampleItinerary.id);
      if (!exists) {
        await repo.insert({
          ...sampleItinerary,
          createdAt: now,
          updatedAt: now,
        });
      }
    }
    return;
  }

  // Insert sample itineraries if database is empty
  for (const itinerary of sampleItineraries) {
    await repo.insert({
      ...itinerary,
      createdAt: now,
      updatedAt: now,
    });
  }
};

